name: Docker CI/CD Workflow

on:
  push:
    branches:
      - main  # Triggers when code is pushed to main

jobs:
  dockerize:
    runs-on: ubuntu-latest
    name: Build and Upload Docker Image

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construct Docker Image
        run:  docker build -t ssaraah97/homeeork:stable .

      - name:  Upload Image to Docker Hub
        run:   docker push ssaraah97/homeeork:stable
    